on: push

name: Build app ionic
jobs:
  build:
   runs-on: ubuntu-latest
     strategy:
        matrix:
         node-version: [16.x]
    steps:
     - uses: actions/checkout@v1
     
     - name: Cache node_modules
        uses: actions/cache@v1
        with:
         path: ~/.npm
         key: ${{runner.os}}-node-${{hasFiles('**/package-lock.json')}}
         restore-keys: |
           ${{runner.os}}-node-
      - name: Node ${{matric.node-version}}    
        uses: actions/setup-node@v1
        with:
         node-version: ${{matrix.no-version}}
      - name: npm install and run build
        run: |
         npm i
         npm run build
